### ISSUE TITLE
Alternate formatting options

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/hms#14]
- Format also days
- Format only minutes and seconds
- Format with nanosecond precision (#75)

Via subclasses "dhms" and "ms" or others, see https://github.com/rstats-db/hms/issues/12#issuecomment-218591746.

**Comment by krlmlr** [comment]
Minutes and seconds are now formatted automatically if the hour is missing.

**Comment by randomgambit** [comment]
Hello @krlmlr , I think this is a related bug

```
> df %>% head()
# A tibble: 6 x 3
     X1 timestamp_utc dum
  <int> <chr>             <dbl>
1     0 16:00:00         0     
2     1 16:00:01         0     
3     2 16:00:02         0   
````
and now my beloved seconds disappear 

```
df %>% head() %>%  mutate(timestamp_utc = as.hms(timestamp_utc))

# A tibble: 6 x 3
     X1 timestamp_utc dum
  <int> <time>            <dbl>
1     0 16:00            0     
2     1 16:00            0     
3     2 16:00            0     
4     3 16:00            0   

```
despite setting `options(digits.secs=4)`
What is the issue here?

Thanks!

**Comment by randomgambit** [comment]
@krlmlr wrapping `format()` around the `hms()` call would output a character. so its not a solution either...
Thanks!

**Comment by krlmlr** [comment]
Thanks. Could you please file a new issue?

**Comment by krlmlr** [comment]
Shelved for now.
