### ISSUE TITLE
is hms similar to between_time in Pandas?

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/hms#27]
Hello there!

I am wondering is one can use this package to slice a dataframe according to the time in the day. 

I am looking for something similar to Pandas' `between_time` (http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.between_time.html)

If so, that would be very useful because there is no function to do cleanly that in R, except by converting the time into a string such as `05:00:02` and performing string-based comparisons (which can be error prone) like `filter(time_str > "08:00:00")`

Thanks!

**Comment by ellisvalentiner** [comment]
You can likely use `hms` for this but is very straightforward using `dplyr` and `lubridate`.

```r
mydata %>%
  filter(hour(datetimevar) > 8)
```

**Comment by randomgambit** [comment]
@ellisvalentiner a-ha! unfortunately it is not that simple..

Try to filter a dataframe between `19:59` and `22:38` using your technique for instance... This becomes super ugly pretty quick. This is why `between_time` in Pandas is so useful. Maybe you can do something similar here?

**Comment by ellisvalentiner** [comment]
Sure, it is the same idea:

```r
# Sample data for reproducible example
mydata <- data.frame(
  datetimevar = seq(
    from = as.POSIXct("2017-04-13 00:00:00"),
    to = as.POSIXct("2017-04-14 00:00:00"),
    by = 1))

mydata %>%
  # Extract just the time component
  mutate(
    just_time = as.hms(strftime(datetimevar, format = "%T"))
  ) %>%
  # Then filter or slice as you normally would
  filter(just_time > as.hms("19:59:00") & just_time < as.hms("22:38:00"))
```

**Comment by randomgambit** [comment]
sweet

**Comment by randomgambit** [comment]
can we install this package without `devtools`? On my machine at work, I cannot install rtools....

**Comment by ellisvalentiner** [comment]
The package is available on CRAN: https://cran.r-project.org/web/packages/hms/

**Comment by randomgambit** [comment]
@ellisvalentiner but is `hms` able to handle milliseconds? Milliseconds info seem to disappear..

```
mydata <- data.frame(
  datetimevar = seq(
    from = as.POSIXct("2017-04-13 00:00:00.500", format = "%Y-%m-%d %H:%M:%OS" ),
    to = as.POSIXct("2017-04-14 00:00:00.400", format = "%Y-%m-%d %H:%M:%OS"),
    by = 1))

mydata %>% mutate(just_time = as.hms(strftime(datetimevar, format = "%H:%M:%OS"))) %>% head(.)
```

gives
```
            datetimevar just_time
1 2017-04-13 00:00:00.5  00:00:00
2 2017-04-13 00:00:01.5  00:00:01
3 2017-04-13 00:00:02.5  00:00:02
4 2017-04-13 00:00:03.5  00:00:03
5 2017-04-13 00:00:04.5  00:00:04
6 2017-04-13 00:00:05.5  00:00:05
