### ISSUE TITLE
as.hms.POSIXct should respect time zone

### ISSUE THREAD

**Issue by hadley** [tidyverse/hms#28]
Or there should be another function that allows you to extract the clock time from a POSIXct object (because it's often useful to separate a date time into a date and a time)

**Comment by hadley** [comment]
It might better to have a separate function for this which takes an explicit tz — this is useful when you have a vector of datetimes in UTC and a vector of local time zones and want to get the local time of day.

**Comment by krlmlr** [comment]
I feel this is out of scope for this package. Isn't there an equivalent lubridate function?

**Comment by hadley** [comment]
It feels like this is going to be a common way to create hms objects - it's often useful to partition a date-time into a date and a time. That feels very much in scope for hms (and I don't think there's an existing lubridate function for this)

**Comment by krlmlr** [comment]
I have found `x - lubridate::floor_date(x, "days")`, and `lubridate::with_tz()`. Happy to implement `lubridate::time_of_day()` (which should return a `Duration`) and `as.hms()` methods in `lubridate`.

You described a common way to create time-of-day objects, but if you're dealing with timestamps, using lubridate seems a good idea anyway. I'd like to restrict the scope of hms, so unless there's a compelling reason to extend this package to handle dates, I'd prefer implementing ths in lubridate. Are we going to integrate lubridate in the tidyverse, or will there be a modern successor?

**Comment by krlmlr** [comment]
`as.hms.POSIXt()` now has a `tz` argument.

**Comment by hadley** [comment]
It should default to the `tz` in `x`?

**Comment by krlmlr** [comment]
Perhaps yes, but that would break compatibility. If this is important, I'd add a pkgconfig switch.

**Comment by hadley** [comment]
I think it's probably fine to break compatibility given the number of uses, and the likelihood that anyone actually wants the local time in UTC.

**Comment by krlmlr** [comment]
Agreed. The new default is now the local tz. I'd like to promote "pkgconfig" usage even if few will use it here.
