### ISSUE TITLE
as.hms should be able to parse if no seconds

### ISSUE THREAD

**Issue by hadley** [tidyverse/hms#30]
```
> hms::as.hms("05:00")
NA
```

**Comment by krlmlr** [comment]
We could support `as.hms("05:00", "%H:%M")`, but I'm not sure we should accept this unconditionally.?

**Comment by hadley** [comment]
Unconditionally seems reasonable to me

**Comment by krlmlr** [comment]
Added `parse_hm()` and `parse_hms()`, because I think it's better to be explicit. `as.hms()` forwards to `parse_hms()`.
