### ISSUE TITLE
can hms handle milliseconds?

### ISSUE THREAD

**Issue by randomgambit** [tidyverse/hms#33]
I am using `hms` to parse the time (hour,  minutes, seconds, milliseconds) from timestamps in my data.
Unfortunately, I notice that `hms` seems to forget about the millisecond part of a time (in character format).

```
> as.hms("12:34:56")
12:34:56
> as.hms("12:34:56.542")
12:34:56
> options(digits.secs=3)
> as.hms("12:34:56.542")
12:34:56
```
Is that a bug? Having milliseconds is important because I sort the data according to time...

**Comment by krlmlr** [comment]
Thanks for reporting!

**Comment by krlmlr** [comment]
Fixed in the development version.

**Comment by randomgambit** [comment]
you re welcome!. I am an hardcore user of intraday timestamps, so im happy to report any bugs. 
When are the updates expected to be on CRAN? I cannot use `devtools` at work (need to install from zip)

**Comment by krlmlr** [comment]
No ETA yet. Can you build a .tar.gz at home using `R CMD build`?

**Comment by randomgambit** [comment]
never done so. how can I do that?

**Comment by krlmlr** [comment]
Download or clone the repository from GitHub, extract, and run `R CMD build .` from the terminal.
