### ISSUE TITLE
 Implicit coercion when operating with strings 

### ISSUE THREAD

**Issue by qgeissmann** [tidyverse/hms#38]
I personally find it quite useful to be able to implicitly coerce strings to time objects.
I believe this is implemented in POSIXct. For instance: `as.POSIXct("2016-01-01") == "2016-01-01"` is `TRUE`.
In hms, we could be writing `x > "23:50:21.100"` instead of `x > hms(21.100, 50,23)` (or explicitly using `as.hms()`).
Now, we have:
```R
> hms(1) > "00:00:02"
#> TRUE 
```
I am happy to implement this new feature if you want

**Comment by krlmlr** [comment]
I'd rather be explicit here, and not coerce implicitly.

**Comment by krlmlr** [comment]
Seems we can't define `Ops.hms()` without breaking things (#18). Would we need that to change the behavior of `>` ?
