### ISSUE TITLE
parser can be improved

### ISSUE THREAD

**Issue by qgeissmann** [tidyverse/hms#39]
- [ ] "XX:YY"  should implicitly mean, and be parsed as, "HH:MM". Now, we have `as.hms("12:00") = NA`
- [ ] Negative durations such as `-10:21:00` could be parsed as well `as.hms("-12:00:01") = NA`
- [ ] Days should be parsed either with `Dd`, `DdHH:MM`, or `DdHH:MM:SS` (especially if we make a `dhms` class, see #12). Decimal number of days should only be allowed when no hour is provides (e.g. "0.5d12:00:11" does not make sense).
- [ ] We should be able to parse durations greated that 24h. Now, we get `as.hms("24:00:01") = NA`. This is unexpected since we display `hms(86401)` as "24:00:01".
- [ ] Check format more stingeantly. At the moment, `as.hms("21:00:0012ABC")` is "21:00:12". `as.hms("21:1:00")` is "21:01:12".
- [ ] Give warnings or errors when format is not respected, or inconsistent. For now, we have `NA` without always knowing why. For instance `as.hms("21:61:00")` and `as.hms("hello")` both give `NA`, and no warning/error. 

I attempted a prototypical parser that addresses these issues (https://github.com/qgeissmann/dhms). I am happy to work on it and merge it.

**Comment by krlmlr** [comment]
Agreed that we should be able to round-trip correctly.

@hadley: Should `as.hms.character()` give a warning if it cannot parse its arguments, perhaps optionally?

**Comment by hadley** [comment]
I think you should follow the convention of readr (and base R), which, IIRC, is to warn whenever there is a failure.  It'd be more work, but it's probably worth it, to return a problems data frame as an attribute like in readr, as that way you can also use `stop_for_problems()`.

**Comment by qgeissmann** [comment]
Thanks, I will study how it is implemented in `readr` and follow the convention before I submit a PR

**Comment by krlmlr** [comment]
The parser here is very simple, sophisticated parsing is outside the scope of this package.
