### ISSUE TITLE
`dhms` class should be implemented

### ISSUE THREAD

**Issue by qgeissmann** [tidyverse/hms#40]
When durations are larger than several days, the "HH:MM:SS" becomes quite hard to grasp. 
Most people will not intuitively get that "162:00:00"= "6d18:00:00". As discussed in #12. it could be very useful to provide another class, `dhms`, that displays durations in days and HMS, as well.
I am happy to implement it

**Comment by krlmlr** [comment]
Thanks, this would be useful indeed.

**Comment by krlmlr** [comment]
Duplicate of #14.

**Comment by krlmlr** [comment]
Shelved for now.
