### ISSUE TITLE
space between minus sign and first number 

### ISSUE THREAD

**Issue by qgeissmann** [tidyverse/hms#47]
Not sure this is a feature or a bug, but when we print a vector of negative durations, minus signs are left justified --  whilst numbers are right justified.
Personally, I find it harder to read if `-` is not immediatly in front of a number:
```R
- hms(hours = c(1, 1000))
#> -  01:00:00
#> -1000:00:00
```

**Comment by krlmlr** [comment]
This is consistent with the output in a tibble column, let's keep it the way it is now.
