### ISSUE TITLE
Addition respects 24hour cycles

### ISSUE THREAD

**Issue by DocEd** [tidyverse/hms#59]
Would it be useful to have a modification that permitted hms objects to roll over at 24 hour boundaries? For example

22:00:00 + 03:00:00 = 01:00:00

At the moment it equals 25:00:00

I have a specific case use at the moment that would make this adjustment incredibly useful.

**Comment by krlmlr** [comment]
Thanks. This is not how the underlying `"difftime"` class works. Can you use "regular" date-times and extract the time-of-day part? Alternatively, you could use `as.hms(as.numeric(x) %% 86400)` .
