### ISSUE TITLE
Use maybe_lossy_cast()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/hms#68]
in `vec_cast.hms.character()` as soon as it becomes available.

**Comment by krlmlr** [comment]
Now `allow_lossy_cast()` .

**Comment by krlmlr** [comment]
`maybe_lossy_cast()` also exists.

@lionel-: Are you planning substantial changes to `maybe_lossy_cast()`? Is it safe to use here?

**Comment by lionel-** [comment]
I would say this is a more experimental area of vctrs. It doesn't seem to be very useful either. Do you really need this? I would avoid throwing lossy cast conditions and just throw coercion errors personally. That said if you really need it go ahead, there are no changes planned now (but vctrs is not under active dev at the moment).

**Comment by krlmlr** [comment]
Thanks, throwing an error now.
