### ISSUE TITLE
Does hms handles precision up to nanosecond ?

### ISSUE THREAD

**Issue by statquant** [tidyverse/hms#74]
Hello, I have a simple question regarding this package.
Does the precision allows for use of nanoseconds ?

**Comment by krlmlr** [comment]
In principle yes, but the output format doesn't show nanoseconds yet. Let's discuss in #75.

``` r
hms::hms(1e-9) * 1e6
#> Time difference of 0.001 secs
```

<sup>Created on 2019-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
