### ISSUE TITLE
Change display precision

### ISSUE THREAD

**Issue by statquant** [tidyverse/hms#75]
Hello, is it possible to modify globally the display format of hms ? I'd like to show nanosecond resolution.
Regards

**Comment by krlmlr** [comment]
Thanks. What output format do you suggest? How many significant digits do you require in your use case?

**Comment by statquant** [comment]
Hello, maybe the easiest would be to have a global options("hms.display_format").
For my usecase I require nanoseconds 01:23:45.000000001
This being said it could also be an attribute which have advantages of allowing different display but a lot more work I would imagine.
Regards

**Comment by statquant** [comment]
nanotime already provide all the required features and more.
