### ISSUE TITLE
Add digits argument to round_hms() and trunc_hms()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/hms#78]
`round_hms(digits = 1)` would map to `round_hms(secs = 0.1)`; `round_hms(digits = -2)` would map to `round_hms(secs = 60)` .

**Comment by hglanz** [comment]
I'm tackling this for tidy-dev-day 2020. Will finish remotely.

First draft of changes are in forked repo, with error messages and documentation left to finish.
