### ISSUE TITLE
Implement comparaison with character and -/+

### ISSUE THREAD

**Issue by statquant** [tidyverse/hms#79]
Hello, that would be great if hms could implement comparaison with character like `Date` or `nanotime`, right now it does not throw and the result is wrong
```r
as_hms("16:00:00") < "16:30:00"
[1] FALSE
```

That would also be great if we could use operators - and +
```r
# class is lost
as_hms("16:00:00") - 1
Time difference of 57599 secs
# class is lost
as_hms("16:00:00") - as_hms("00:00:01")
Time difference of 57599 secs
# I'd expect this result
as_hms(as_hms("16:00:00") - 1)
15:59:59
```

**Comment by krlmlr** [comment]
Thanks.

I don't think that comparison with a string is a good idea, can you parse before comparing to make it explicit?

``` r
library(hms)
as_hms("16:00:00") < as_hms("16:30:00")
#> [1] TRUE
as_hms("17:00:00") < as_hms("16:30:00")
#> [1] FALSE
```

<sup>Created on 2019-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Unfortunately, the current design makes it very difficult to preserve the `"hms"` class after arithmetic operations, again you need to coerce with `as_hms()`. Original issue: #18.

**Comment by statquant** [comment]
Hello, I can definitely make it explicit but truth is I do not really want to. I guess you're afraid people start silently to use comparison on 1000000s of items, maybe we can check for right end side to be of lenghth 1 ?
