### ISSUE TITLE
vec_math() and vec_arith() for hms

### ISSUE THREAD

**Issue by earowang** [tidyverse/hms#85]
Possible to have `vec_math()` and `vec_arith()` support for hms?

``` r
x <- hms::hms(hours = 0:9)
min(x)
#> Time difference of 0 secs
max(x)
#> Time difference of 32400 secs
x + 60
#> Time differences in secs
#>  [1]    60  3660  7260 10860 14460 18060 21660 25260 28860 32460
```

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by krlmlr** [comment]
Thanks. I've tried multiple times in the past to no avail, it may be worth another shot with vctrs.

**Comment by krlmlr** [comment]
Unfortunately, `vec_math()` and `vec_arith()` don't help here. Certain coercions are baked deeply into base R, see https://github.com/tidyverse/hms/issues/18#issuecomment-344738097 for context.

**Comment by krlmlr** [comment]
It might be possible after all, tracked in #18.
