### ISSUE TITLE
Re-license as MIT

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/hms#86]
I have reviewed all non-RStudio [contributors](https://github.com/tidyverse/hms/graphs/contributors). I think the following contribution[s] are significant enough to merit a potential copyright claim:

* [x] [those made](https://github.com/tidyverse/hms/commits?author=qgeissmann) by @qgeissmann  
* [x] [those made](https://github.com/tidyverse/hms/commits?author=vspinu) by @vspinu  

@qgeissmann, @vspinu, would you permit us to relicense hms with the MIT license? This is part of a general effort to make the licensing across r-lib and tidyverse as simple and consistent as possible. If so, please comment "I agree" below.

cc @hadley

**Comment by vspinu** [comment]
I agree.

  Vitalie

**Comment by batpigandme** [comment]
Hi @qgeissmann,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by qgeissmann** [comment]
Hi there, of course!
I agree. Thanks for asking!
Quentin
